name: Database Migration

on:
  push:
    branches: [main]
    paths:
      - 'prisma/schema.prisma'
      - 'prisma/migrations/**'
  workflow_dispatch: # 手動実行も可能

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Verify pnpm installation
        run: |
          which pnpm
          pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm run db:prisma-generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Check for pending migrations
        id: check-migrations
        run: |
          # 保留中のマイグレーションがあるかチェック
          if pnpm prisma migrate status | grep -q "Following migration have not yet been applied"; then
            echo "has_pending=true" >> $GITHUB_OUTPUT
          else
            echo "has_pending=false" >> $GITHUB_OUTPUT
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Apply migrations
        if: steps.check-migrations.outputs.has_pending == 'true'
        run: |
          echo "Applying pending migrations..."
          pnpm prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Verify migration status
        run: |
          echo "Migration status:"
          pnpm prisma migrate status
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Database migrations completed successfully!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Database migration failed!"
          exit 1
